uknow_platform_recherche:
    resource: "@UknowPlatformBundle/Resources/config/routing/recherche.yml"
    prefix:   /recherche

uknow_platform_actualites:
    resource: "@UknowPlatformBundle/Resources/config/routing/actualites.yml"
    prefix:   /actualites

uknow_platform_cartable:
    resource: "@UknowPlatformBundle/Resources/config/routing/cartable.yml"
    prefix:   /cartable

uknow_platform_ajouter:
    resource: "@UknowPlatformBundle/Resources/config/routing/ajouter.yml"
    prefix:   /ajouter

uknow_platform_evaluation:
    resource: "@UknowPlatformBundle/Resources/config/routing/evaluation.yml"
    prefix:   /evaluation

uknow_platform_compte:
    resource: "@UknowPlatformBundle/Resources/config/routing/compte.yml"
    prefix:   /compte

uknow_platform_donnees:
    resource: "@UknowPlatformBundle/Resources/config/routing/donnees.yml"
    prefix:   /donnees

uknow_platform_ajax:
    resource: "@UknowPlatformBundle/Resources/config/routing/ajax.yml"
    prefix:   /ajax

uknow_platform_modifier:
    resource: "@UknowPlatformBundle/Resources/config/routing/modifier.yml"
    prefix:   /modifier





