uknow_platform:
    resource: "@UknowPlatformBundle/Resources/config/routing.yml"
    prefix:   /

uknow_utilisateur:
    resource: "@UknowUtilisateurBundle/Resources/config/routing.yml"
    prefix:   /

