security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE USER, ROLE AUTEUR, ROLE MODERATEUR]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main_login:
            pattern:   ^/(connexion$|inscription/)
            anonymous: true

        main:
            pattern: ^/
            provider: fos_userbundle
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path:   fos_user_security_logout
                target: fos_user_security_login
            anonymous:  true
            remember_me:
                key:    %secret%

    access_control:
        - { path: ^/connexion$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inscription/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/ajouter, roles: ROLE_USER }
        - { path: ^/recherche, roles: ROLE_USER }
        - { path: ^/admin/, role: ROLE_ADMIN }
