<?php

namespace Uknow\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DonneesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonneesRepository extends EntityRepository
{
}
