Uknow\PlatformBundle\Entity\Donnees:
    type: entity
    table: null
    repositoryClass: Uknow\PlatformBundle\Entity\DonneesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        domaine_nom:
            type: string
            length: 255
        domaine_lien:
            type: string
            length: 255
        matiere_nom:
            type: string
            length: 255
        matiere_lien:
            type: string
            length: 255
        theme_nom:
            type: string
            length: 255
        theme_lien:
            type: string
            length: 255
        chapitre_nom:
            type: string
            length: 255
        chapitre_lien:
            type: string
            length: 255
        titre:
            type: string
            length: 255
        texte:
            type: text
        correction:
            type: text
            nullable: true
        date:
            type: datetime
        modification:
            type: integer
        pertinent:
            type: integer
        developper:
            type: integer
        inutile:
            type: integer
        type:
            type: string
            length: 255
        niveau_nom:
            type: string
            length: 255
        niveau_lien:
            type: string
            length: 255
        fiabilite:
            type: integer
        temps:
            type: integer
            nullable: true
    lifecycleCallbacks: {  }