Uknow\PlatformBundle\Entity\Structure:
    type: entity
    table: null
    repositoryClass: Uknow\PlatformBundle\Entity\StructureRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        domaine:
            type: string
            length: 255
        domaineLien:
             type: string
             length: 255
        matiere:
            type: string
            length: 255
        matiereLien:
            type: string
            length: 255
        theme:
            type: string
            length: 255
        themeLien:
            type: string
            length: 255
        chapitre:
            type: string
            length: 255
        chapitreLien:
            type: string
            length: 255
    lifecycleCallbacks: {  }