uknow_platform_ajax_autocompletion:
    path:     /autocompletion
    defaults: { _controller: UknowPlatformBundle:Ajax:autocompletion }

uknow_platform_ajax_enregistrement:
    path:     /enregistrement
    defaults: { _controller: UknowPlatformBundle:Ajax:enregistrement }

uknow_platform_ajax_suppression:
    path:     /suppression
    defaults: { _controller: UknowPlatformBundle:Ajax:suppression }