uknow_platform_cartable_cours:
    path:     /cours
    defaults: { _controller: UknowPlatformBundle:Cartable:cours}

uknow_platform_cartable_exercices:
    path:     /exercices
    defaults: { _controller: UknowPlatformBundle:Cartable:exercices}

uknow_platform_cartable_matieres:
    path:     /{matiere}
    defaults: { _controller: UknowPlatformBundle:Cartable:matiere}

uknow_platform_cartable_niveaux:
    path:     /{niveau}
    defaults: { _controller: UknowPlatformBundle:Cartable:niveaux}