uknow_platform_compte_parametres:
    path:     /parametres
    defaults: { _controller: UknowPlatformBundle:Evaluation:test}
    
uknow_platform_compte_progression:
    path:     /progression
    defaults: { _controller: UknowPlatformBundle:Evaluation:progression}
    
uknow_platform_evaluation_niveau:
    path:     /niveaux
    defaults: { _controller: UknowPlatformBundle:Evaluation:niveaux}