uknow_platform_donnees_modification:
    path:     /modifications/{id}
    defaults: { _controller: UknowPlatformBundle:Donnees:modifications, id: null}

uknow_platform_donnees_rechercher:
    path:     /rechercher
    defaults: { _controller: UknowPlatformBundle:Donnees:rechercher}