uknow_platform_evaluation_exercice:
    path:     /test
    defaults: { _controller: UknowPlatformBundle:Evaluation:exercice}

uknow_platform_evaluation_test:
    path:     /test
    defaults: { _controller: UknowPlatformBundle:Evaluation:test}

uknow_platform_evaluation_examen:
    path:     /test
    defaults: { _controller: UknowPlatformBundle:Evaluation:examen}

uknow_platform_evaluation_resultats:
    path:     /resultats
    defaults: { _controller: UknowPlatformBundle:Evaluation:resultats}

uknow_platform_evaluation_corriger:
    path:     /corriger
    defaults: { _controller: UknowPlatformBundle:Evaluation:corriger}