uknow_platform_recherche_acceuil:
    path:     /
    defaults: { _controller: UknowPlatformBundle:Structure:structure, domaine: null, matiere: null, theme:null, chapitre:null}

uknow_platform_recherche_domaine:
    path:     /{domaine}
    defaults: { _controller: UknowPlatformBundle:Structure:structure, matiere: null, theme:null, chapitre:null}

uknow_platform_recherche_matiere:
    path:     /{domaine}/{matiere}
    defaults: { _controller: UknowPlatformBundle:Structure:structure, theme:null, chapitre:null }

uknow_platform_recherche_theme:
    path:     /{domaine}/{matiere}/{theme}
    defaults: { _controller: UknowPlatformBundle:Structure:structure, chapitre:null }

uknow_platform_recherche_chapitre:
    path:     /{domaine}/{matiere}/{theme}/{chapitre}
    defaults: { _controller: UknowPlatformBundle:Donnees:recherche}