uknow_platform_recherche_acceuil:
    path:     /
    defaults: { _controller: UknowPlatformBundle:Structure:structure, lienDomaine: null, lienMatiere: null, lienTheme:null }

uknow_platform_recherche_modification:
    path:     /{lettres}/modifications/{id}
    defaults: { _controller: UknowPlatformBundle:Structure:modifications}

uknow_platform_recherche_domaine:
    path:     /{lienDomaine}
    defaults: { _controller: UknowPlatformBundle:Structure:structure, lienMatiere: null, lienTheme:null }

uknow_platform_recherche_matiere:
    path:     /{lienDomaine}/{lienMatiere}
    defaults: { _controller: UknowPlatformBundle:Structure:structure, lienTheme:null }

uknow_platform_recherche_theme:
    path:     /{lienDomaine}/{lienMatiere}/{lienTheme}
    defaults: { _controller: UknowPlatformBundle:Structure:structure}

uknow_platform_recherche_chapitre:
    path:     /{lienDomaine}/{lienMatiere}/{lienTheme}/{lienChapitre}
    defaults: { _controller: UknowPlatformBundle:Donnees:recherche, id: null}

uknow_platform_recherche_id:
    path:     /{lienDomaine}/{lienMatiere}/{lienTheme}/{lienChapitre}/{id}
    defaults: { _controller: UknowPlatformBundle:Donnees:recherche}

