<?php
/**
 * Created by PhpStorm.
 * User: thomas
 * Date: 25/02/15
 * Time: 22:11
 */

namespace Uknow\UtilisateurBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CompteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompteRepository extends EntityRepository{

}